import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { connectBrowser } from "./browser-runtime.js";
import { OperationalMemory } from "./operational-memory.js";
import { z } from "zod";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const server=new McpServer({name:"jimmy-bridge",version:"0.4.6"});
const memory=new OperationalMemory();
let browser,context,page,pending=null,browserSession=null,changes=[];
function loadPending(){try{const x=JSON.parse(fs.readFileSync(PENDING_FILE,"utf8"));return x.expires>Date.now()?x:null}catch{return null}}
const PROTECTED=/publish|delete|remove|destroy|billing|password|security|credential|account|make live|go live/i;
const APPROVAL_DIR=path.join(os.homedir(),".jimmy-bridge");
const APPROVAL_FILE=path.join(APPROVAL_DIR,"publish-approval.json");
const PENDING_FILE=path.join(APPROVAL_DIR,"pending-publish.json");
fs.mkdirSync(APPROVAL_DIR,{recursive:true});
pending=loadPending();
const ok=data=>({content:[{type:"text",text:JSON.stringify(data)}]});
const sessionId=()=>browserSession||"no-session";
function clearApproval(){try{fs.unlinkSync(APPROVAL_FILE)}catch{}}
function readApproval(){try{return JSON.parse(fs.readFileSync(APPROVAL_FILE,"utf8").replace(String.fromCharCode(0xFEFF),""))}catch{return null}}
async function getPage(){if(page&&!page.isClosed())return page;const r=await connectBrowser();browser=r.browser;context=r.context;page=r.page;browserSession=r.sessionId;if(pending&&pending.session!==browserSession){pending=null;clearApproval();try{fs.unlinkSync(PENDING_FILE)}catch{}}return page;}
async function snap(p){return p.locator("body").evaluate(()=>{const vis=e=>!!(e.offsetWidth||e.offsetHeight||e.getClientRects().length),nm=e=>(e.getAttribute("aria-label")||e.getAttribute("title")||e.innerText||e.value||e.placeholder||"").trim();return{title:document.title,url:location.href,headings:[...document.querySelectorAll("h1,h2,h3")].filter(vis).map(e=>e.innerText.trim()).slice(0,40),fields:[...document.querySelectorAll("input,textarea,[contenteditable=true]")].filter(vis).map((e,i)=>({index:i,label:(e.labels&&e.labels[0]?.innerText||e.getAttribute("aria-label")||e.placeholder||e.name||e.id||"").trim(),value:e.value??e.innerText})).slice(0,60),controls:[...document.querySelectorAll("button,a,[role=button],input[type=button],input[type=submit]")].filter(vis).map((e,i)=>({index:i,name:nm(e),protected:/publish|delete|remove|destroy|billing|password|security|credential|account|make live|go live/i.test(nm(e))})).slice(0,80),status:[...document.querySelectorAll("[role=status],[aria-live]")].filter(vis).map(e=>e.innerText.trim()).filter(Boolean)};});}
async function target(p,kind,name){const want=name.toLowerCase(),sel=kind==="field"?"input,textarea,[contenteditable=true]":"button,a,[role=button],input[type=button],input[type=submit]",c=p.locator(sel),hits=[];for(let i=0;i<await c.count();i++){const e=c.nth(i),meta=[await e.getAttribute("aria-label"),await e.getAttribute("title"),await e.getAttribute("placeholder"),await e.getAttribute("name"),await e.getAttribute("id"),await e.getAttribute("value"),await e.getAttribute("href"),await e.innerText().catch(()=>"")].filter(Boolean).join(" ").toLowerCase();const lab=kind==="field"?await e.evaluate(el=>el.labels?.[0]?.innerText||"").catch(()=>""):"";if((meta+" "+lab.toLowerCase()).includes(want))hits.push(e);}if(hits.length===0)throw new Error("semantic_target_not_found:"+kind+":"+name);if(hits.length>1)throw new Error("semantic_target_ambiguous:"+kind+":"+name+":"+hits.length);return hits[0];}
server.tool("memory_remember","Remember a reusable website procedure or user terminology. Never store credentials, tokens, cookies, secrets, or authentication material.",{id:z.string(),intent:z.string(),aliases:z.array(z.string()),steps:z.array(z.object({action:z.string(),target:z.string()})),provenance:z.string().optional()},async(p)=>{try{return ok({ok:true,procedure:memory.teach(p)})}catch(e){return ok({ok:false,reason:e.message})}});
server.tool("memory_recall","Recall the best known procedure for the user's natural-language intent. Use this before rediscovering a previously learned website workflow.",{query:z.string()},async({query})=>ok({ok:true,procedure:memory.recall(query)}));
server.tool("memory_outcome","Record whether a recalled procedure actually worked. Success promotes it to VERIFIED; failure marks it STALE so it can be relearned.",{id:z.string(),success:z.boolean()},async({id,success})=>{try{return ok({ok:true,procedure:memory.outcome(id,success)})}catch(e){return ok({ok:false,reason:e.message})}});
server.tool("memory_forget","Forget a stored procedure by id.",{id:z.string()},async({id})=>ok({ok:true,forgotten:memory.forget(id)}));
server.tool("browser_open","Open a website in Jimmy's local browser. Use this instead of filesystem, terminal or read_file for website work.",{url:z.string()},async({url})=>{const u=new URL(url);if(!["http:","https:","file:"].includes(u.protocol))return ok({ok:false,blocked:true,reason:"unsafe_url_scheme"});if(u.protocol==="file:"&&!decodeURIComponent(u.pathname).toLowerCase().includes("/jimmy-bridge/mock/"))return ok({ok:false,blocked:true,reason:"local_file_access_blocked"});const p=await getPage();await p.goto(url,{waitUntil:"domcontentloaded"});pending=null;clearApproval();try{fs.unlinkSync(PENDING_FILE)}catch{};return ok({ok:true,...await snap(p)});});
server.tool("browser_inspect","Inspect current website semantically.",{},async()=>ok({ok:true,...await snap(await getPage())}));
server.tool("browser_set_field","Edit an ordinary field by visible label/name and verify value. Cannot publish.",{field:z.string(),text:z.string()},async({field,text})=>{const p=await getPage(),e=await target(p,"field",field);await e.fill(text);changes.push({field,text});const value=await e.inputValue().catch(async()=>await e.innerText());return ok({ok:value===text,field,value});});
server.tool("browser_safe_action","Activate only NON-DESTRUCTIVE controls. Publish/delete/removal/billing/security/account/credentials are always blocked.",{action:z.string()},async({action})=>{if(PROTECTED.test(action))return ok({ok:false,blocked:true,reason:"protected_action"});const p=await getPage(),e=await target(p,"control",action),meta=[await e.getAttribute("aria-label"),await e.getAttribute("title"),await e.innerText().catch(()=>""),await e.getAttribute("value"),await e.getAttribute("href")].filter(Boolean).join(" ");if(PROTECTED.test(meta))return ok({ok:false,blocked:true,reason:"protected_action"});await e.click();return ok({ok:true,...await snap(p)});});
server.tool("browser_verify","Verify expected visible text, field value or status.",{expected:z.string()},async({expected})=>{const p=await getPage(),body=await p.locator("body").innerText(),vals=await p.locator("input,textarea").evaluateAll(es=>es.map(e=>e.value).join("\n"));return ok({ok:(body+"\n"+vals).includes(expected),expected,...await snap(p)});});
server.tool("request_publish","Request protected publication. This NEVER authorizes or publishes. A separate trusted local human UI must approve outside Gemini.",{},async()=>{const p=await getPage();pending={id:crypto.randomUUID(),created:Date.now(),expires:Date.now()+120000,session:sessionId(),url:p.url(),title:await p.title(),operation:"Publish",changes:changes.slice(-10)};clearApproval();fs.writeFileSync(PENDING_FILE,JSON.stringify(pending),{encoding:"utf8",mode:0o600});try{const {spawn}=await import("node:child_process");const ui=new URL("./approval-helper.ps1",import.meta.url).pathname.replace(/^\/(.:)/,"$1").replace(/%20/g," ");spawn("powershell.exe",["-NoProfile","-STA","-File",ui],{detached:false,stdio:"ignore",windowsHide:false}).unref();}catch{}return ok({ok:true,published:false,state:"AWAITING_HUMAN_APPROVAL",expiresInSeconds:120,summary:{url:pending.url,title:pending.title,operation:pending.operation}});});
server.tool("publish_status","Read publish approval state. No secret or approval capability is returned.",{},async()=>{await getPage();if(!pending)return ok({ok:true,state:"NONE"});if(Date.now()>pending.expires){pending=null;clearApproval();try{fs.unlinkSync(PENDING_FILE)}catch{};return ok({ok:true,state:"EXPIRED"});}const a=readApproval();if(!a||a.id!==pending.id||a.session!==pending.session)return ok({ok:true,state:"AWAITING_HUMAN_APPROVAL"});if(a.decision==="deny"){pending=null;clearApproval();try{fs.unlinkSync(PENDING_FILE)}catch{};return ok({ok:true,state:"DENIED"});}if(a.decision==="approve"&&a.expires>Date.now())return ok({ok:true,state:"APPROVED"});return ok({ok:true,state:"AWAITING_HUMAN_APPROVAL"});});
server.tool("execute_approved_publish","Execute publication only if a separate trusted local human approval already exists. Gemini cannot create that approval.",{},async()=>{await getPage();if(!pending)return ok({ok:false,blocked:true,published:false,reason:"no_pending_publish"});if(Date.now()>pending.expires){pending=null;clearApproval();try{fs.unlinkSync(PENDING_FILE)}catch{};return ok({ok:false,blocked:true,published:false,reason:"approval_expired"});}if(pending.session!==sessionId())return ok({ok:false,blocked:true,published:false,reason:"browser_session_mismatch"});const a=readApproval();if(!a||a.id!==pending.id||a.session!==pending.session||a.decision!=="approve"||a.expires<=Date.now())return ok({ok:false,blocked:true,published:false,reason:"independent_human_approval_required"});clearApproval();pending=null;try{fs.unlinkSync(PENDING_FILE)}catch{};const p=await getPage(),e=await target(p,"control","publish"),meta=[await e.getAttribute("aria-label"),await e.getAttribute("title"),await e.innerText().catch(()=>""),await e.getAttribute("value")].filter(Boolean).join(" ");if(!/publish/i.test(meta))return ok({ok:false,blocked:true,published:false,reason:"publish_control_not_confidently_identified"});await e.click();return ok({ok:true,published:true,...await snap(p)});});
server.tool("browser_close","Close Jimmy browser session and invalidate pending approvals.",{},async()=>{if(browser)await browser.close();browser=context=page=null;pending=null;clearApproval();try{fs.unlinkSync(PENDING_FILE)}catch{};return ok({ok:true});});
await server.connect(new StdioServerTransport());
